<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVMVZ82G\Eccube_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVMVZ82G/Eccube_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVMVZ82G.legacy');

    return;
}

if (!\class_exists(Eccube_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVMVZ82G\Eccube_KernelProdContainer::class, Eccube_KernelProdContainer::class, false);
}

return new \ContainerVMVZ82G\Eccube_KernelProdContainer([
    'container.build_hash' => 'VMVZ82G',
    'container.build_id' => 'd52021df',
    'container.build_time' => 1707903307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVMVZ82G');
